"""Locally cached paralinguistic fillers ("Hmm.", "Good question.", "Hold on.").

Played the instant a user turn is accepted, while the LLM is still generating, so the
agent reacts in ~0 ms instead of going silent for a second. Jev picks the category as
part of the end-of-turn fan-out (no extra round trip); the deterministic policy decides
whether the pick is confident enough to use.

Generated by scripts/make_fillers.py. Clips are Gradium TTS in the bot's own voice, so
the filler and the answer that follows sound like the same speaker.
"""

from __future__ import annotations

import json
import random
import wave
from pathlib import Path

import numpy as np
from loguru import logger

from app.config import BACKEND_DIR
from app.perception.ecapa import trim_silence

FILLER_DIR = BACKEND_DIR / "assets" / "fillers"
CATEGORIES = ("thinking", "acknowledging", "weighing", "reframing", "nuance", "casual")
LEAD_SILENCE_S = 0.02
TAIL_SILENCE_S = 0.08


class Filler:
    __slots__ = ("category", "text", "pcm", "sample_rate", "duration_s")

    def __init__(self, category: str, text: str, pcm: bytes, sample_rate: int):
        self.category = category
        self.text = text
        self.pcm = pcm
        self.sample_rate = sample_rate
        self.duration_s = len(pcm) / 2 / sample_rate


class FillerLibrary:
    """Loads the cached clips into memory once; picks one per category without repeating."""

    def __init__(self, directory: Path = FILLER_DIR):
        self.by_category: dict[str, list[Filler]] = {}
        self.sample_rate = 48000
        self._last: dict[str, str] = {}
        self._probes: dict[str, Filler] = {}
        manifest = directory / "manifest.json"
        if not manifest.exists():
            logger.warning(f"fillers: no manifest at {manifest}; run scripts/make_fillers.py")
            return
        data = json.loads(manifest.read_text())
        self.sample_rate = int(data.get("sample_rate", 48000))
        for clip in data.get("clips", []):
            path = directory / clip["file"]
            if not path.exists():
                continue
            with wave.open(str(path)) as w:
                pcm = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16)
                rate = w.getframerate()
            pcm = self._tighten(pcm, rate)
            f = Filler(clip["category"], clip["text"], pcm.tobytes(), rate)
            if clip["category"] == "probe":
                # Keyed by text: the picker chooses a question, not a category.
                self._probes[clip["text"].strip().lower()] = f
            else:
                self.by_category.setdefault(clip["category"], []).append(f)
        logger.info(
            f"fillers: {sum(len(v) for v in self.by_category.values())} clips in "
            f"{len(self.by_category)} categories"
        )

    @staticmethod
    def _tighten(pcm: np.ndarray, rate: int) -> np.ndarray:
        """Trim the TTS lead-in/out: a filler that starts 300 ms late defeats the point."""
        audio = pcm.astype(np.float32) / 32768.0
        trimmed = trim_silence(audio, rate)
        if len(trimmed) < 0.1 * rate:
            trimmed = audio
        lead = np.zeros(int(LEAD_SILENCE_S * rate), dtype=np.float32)
        tail = np.zeros(int(TAIL_SILENCE_S * rate), dtype=np.float32)
        return (np.concatenate([lead, trimmed, tail]) * 32768.0).astype(np.int16)

    def available(self) -> bool:
        return bool(self.by_category)

    def probe(self, question: str) -> Filler | None:
        """A pre-rendered probe question, if one was generated for this text.

        Probes come from a fixed list, so they can be cached exactly like
        fillers. Returns None when the clip is absent and the caller should
        fall back to synthesis.
        """
        return self._probes.get(question.strip().lower())

    def pick(self, category: str) -> Filler | None:
        clips = self.by_category.get(category)
        if not clips:
            return None
        choices = [c for c in clips if c.text != self._last.get(category)] or clips
        chosen = random.choice(choices)
        self._last[category] = chosen.text
        return chosen
